### ISSUE TITLE
Derivation of speed & alterations to FreqMeasure

### ISSUE THREAD

**Issue by joshgeake** [3zuli/HB100_test#1]
Hi,

Thanks for your Arduino code, it's worked well for my project.
For my project I just want the data to be a raw m/s so I'm interested to know how you derived the constant 19.49 in the following line of code:

`float spd = frequency / 19.49;`

Also, what alteration did you make to the FreqMeasure library?

Thanks again and best wishes,

Josh.

**Comment by 3zuli** [comment]
The calculation is given on the last page of the datasheet: https://www.openimpulse.com/blog/wp-content/uploads/wpsc/downloadables/HB100_Microwave_Sensor_Application_Note.pdf
I didn't change the FreqMeasure library itself. I only took the LCD_Output example and added the frequency to speed calculation and the additional text which is printed out.
